services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:11434:11434"
    networks:
      - llm_net
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_KEEP_ALIVE=2m
    volumes:
      - ollama:/root/.ollama

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    depends_on: [ollama]
    ports:
      - "127.0.0.1:3000:8080"
    networks:
      - llm_net
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OFFLINE_MODE=true
      - COMFYUI_BASE_URL=http://comfyui:8188
    volumes:
      - open-webui:/app/backend/data

  comfyui:
    image: ghcr.io/ai-dock/comfyui:v2-cpu-22.04-v0.2.7
    container_name: comfyui
    restart: unless-stopped
    ports:
      - "127.0.0.1:8188:8188"
    networks:
      - llm_net
    environment:
      - CF_QUICK_TUNNELS=false
      - COMFYUI_ARGS=--listen 0.0.0.0 --port 8188
      - WEB_ENABLE_AUTH=false
    volumes:
      - ./comfy-data/models:/opt/ComfyUI/models
      - ./comfy-data/input:/opt/ComfyUI/input
      - ./comfy-data/output:/opt/ComfyUI/output

  piper-tts:
    image: kamilkrawiec/piper-openai-tts:latest
    container_name: piper-tts
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - llm_net
    volumes:
      - ./piper-data:/data 
  
  # Info: I needed to add additional preveleges to the voicebox container to get it to work properly. I had to execute the following commands to fix permissions on the voicebox container after it was created. 
  # You may need to do this as well if you run into issues.
  # Files from generations directory:
  # docker compose exec --user root voicebox sh -lc \
  # 'chown -R voicebox:voicebox /app/data/generations && chmod u+rwx /app/data/generations'
  # Models directory:
  # docker compose exec --user root voicebox sh -lc \
  # 'chown -R voicebox:voicebox /home/voicebox/.cache/huggingface'
  voicebox:
    build:
      context: ../voicebox
    container_name: voicebox
    restart: unless-stopped

    ports:
      - "127.0.0.1:17600:17493"

    networks:
      - llm_net

    environment:
      - LOG_LEVEL=info
      - NUMBA_CACHE_DIR=/tmp/numba_cache
      - VOICEBOX_FORCE_CPU=1

    volumes:
      - ./voicebox-output:/app/data/generations
      - voicebox-data:/app/data
      - voicebox-hf-cache:/home/voicebox/.cache/huggingface

    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 10G

volumes:
  ollama:
  open-webui:
  comfyui:
  voicebox-data:
  voicebox-hf-cache:

networks:
  llm_net:
    external: true
