services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "127.0.0.1:11434:11434"   
    environment:
      - OLLAMA_HOST=0.0.0.0:11434 
      - OLLAMA_KEEP_ALIVE=2m      
    volumes:
      - ollama:/root/.ollama

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    depends_on: [ollama]
    ports:
      - "127.0.0.1:3000:8080"     
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OFFLINE_MODE=true
    volumes:
      - open-webui:/app/backend/data

volumes:
  ollama:
  open-webui: