version: "3.9"
services:
  jupyterlab:
    image: jupyter/minimal-notebook:python-3.11
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    restart: unless-stopped
